# Matrix operations

(You can take Python4Examples.py as a reference) You must print on console every change or operation performed.

1. Create 2 matrices A and B of 15x15 each with random inputs between -10 and 10.

In [11]:
import numpy as np

a = np.random.randint(-10, 10,  size=(15, 15))
b = np.random.randint(-10, 10,  size=(15, 15))
print("A = \n" + str(a))
print("B = \n" + str(b))

A = 
[[ -1  -2  -2   6   7   2   6 -10  -1  -3  -2   6  -9  -9  -6]
 [ -1   1   6  -6   5 -10   6  -7  -8   3  -8   4  -9  -8 -10]
 [  5   9 -10  -4   4   6   4   3  -1   1   4   1   6   1   8]
 [ -2  -7   4   8  -2   7   1   6  -4   1   3 -10   3  -1   9]
 [  2  -1  -9  -6   7  -5  -5   2   6   8   1  -4   7   6   6]
 [ -5   6   9   5  -2  -4  -1   9  -8   7  -2  -1  -8  -5   7]
 [-10   1  -1  -9   7  -5 -10   6   9  -1   3  -4  -2  -2  -9]
 [ -5  -8  -5   1  -7   0  -8  -9   5 -10   5   8  -4   6  -9]
 [ -7  -8   3   9   5   4  -3   9   9   5   9  -5  -3  -6   1]
 [  1  -8   2  -6  -3  -1   3  -2  -2   8   1   5   0  -2  -5]
 [ -5  -5   3   2 -10  -8  -9  -6   6  -9   0   8  -9   8   4]
 [-10   9  -6  -9   4   7   5   9  -9  -9   1   8   0   4  -9]
 [  0   7   6   9   9  -6   0   0 -10   7  -8  -2   7  -3   8]
 [  4  -5   7   6  -6  -6  -8  -2  -5   5  -8   7  -3   4   0]
 [ -5  -2  -8   0 -10  -8  -4   5  -2  -7  -1   3   5 -10   1]]
B = 
[[  1  -1   4 -10   8   5  -1   9  -2  -1  -

2. Change the diagonals of both matrices to different values using np.fill_diagonal.

In [19]:
np.fill_diagonal(a, 0)
np.fill_diagonal(b, 0)

print("A = \n" + str(a))
print("B = \n" + str(b))

A = 
[[  0  -2  -2   6   7   2   6 -10  -1  -3  -2   6  -9  -9  -6]
 [ -1   0   6  -6   5 -10   6  -7  -8   3  -8   4  -9  -8 -10]
 [  5   9   0  -4   4   6   4   3  -1   1   4   1   6   1   8]
 [ -2  -7   4   0  -2   7   1   6  -4   1   3 -10   3  -1   9]
 [  2  -1  -9  -6   0  -5  -5   2   6   8   1  -4   7   6   6]
 [ -5   6   9   5  -2   0  -1   9  -8   7  -2  -1  -8  -5   7]
 [-10   1  -1  -9   7  -5   0   6   9  -1   3  -4  -2  -2  -9]
 [ -5  -8  -5   1  -7   0  -8   0   5 -10   5   8  -4   6  -9]
 [ -7  -8   3   9   5   4  -3   9   0   5   9  -5  -3  -6   1]
 [  1  -8   2  -6  -3  -1   3  -2  -2   0   1   5   0  -2  -5]
 [ -5  -5   3   2 -10  -8  -9  -6   6  -9   0   8  -9   8   4]
 [-10   9  -6  -9   4   7   5   9  -9  -9   1   0   0   4  -9]
 [  0   7   6   9   9  -6   0   0 -10   7  -8  -2   0  -3   8]
 [  4  -5   7   6  -6  -6  -8  -2  -5   5  -8   7  -3   0   0]
 [ -5  -2  -8   0 -10  -8  -4   5  -2  -7  -1   3   5 -10   0]]
B = 
[[  0  -1   4 -10   8   5  -1   9  -2  -1  -

3. Make the sum, difference, product between A and B.

In [20]:
print("A + B = \n" + str(a+b))
print("A - B = \n" + str(a-b))
print("A * B = \n" + str(a*b))

A + B = 
[[  0  -3   2  -4  15   7   5  -1  -3  -4  -6  11  -9 -14   3]
 [  2   0   4  -5  -5  -8  -3 -17 -16  -5  -7  -5  -1 -16 -20]
 [ -2  14   0  -7   0  15  -2  -6 -11   0  -4  -4   2   7   4]
 [-11 -13  -6   0   7   6  -1  11  -4  -5  10  -9   0   2   8]
 [  8  -7 -17  -1   0  -5  -2  -1   5  -2   8   0  -2   5  13]
 [-15   9  15   5  -9   0 -10   2  -6   3   7   7 -17  -2   9]
 [ -3   2  -2 -19   5 -14   0   2   4 -11  -7  -9  -7  -7  -3]
 [ -2  -9 -14   7  -8  -9 -15   0  -5  -8  10  16   1   1  -4]
 [ -9  -1  12  16   9  -2  -3  15   0   5  15   0  -1  -9  -7]
 [  6  -3  -7   0   5  -3  -5 -10  -6   0   0   4   2   6  -3]
 [ -8  -5   1   2 -12  -5  -5   1  -2  -7   0  16  -7  -1   8]
 [ -3   4 -16  -6   5  16   9   0 -13 -17   1   0   8  -4   0]
 [  5  14  -1  12  14  -5  -3  -7  -4   3  -9   5   0 -12  10]
 [ -5  -1  -2  14  -9 -14 -17   4   0   6 -18   8  -6   0   1]
 [ -7   0 -14  -4 -19   0  -4   3   4   0   3   8  10  -6   0]]
A - B = 
[[  0  -1  -6  16  -1  -3   7 -19   

4. Find the transpose of A and B.

In [21]:
print("A^T = \n " + str(a.transpose()))
print("B^T = \n " + str(b.transpose()))

A^T = 
 [[  0  -1   5  -2   2  -5 -10  -5  -7   1  -5 -10   0   4  -5]
 [ -2   0   9  -7  -1   6   1  -8  -8  -8  -5   9   7  -5  -2]
 [ -2   6   0   4  -9   9  -1  -5   3   2   3  -6   6   7  -8]
 [  6  -6  -4   0  -6   5  -9   1   9  -6   2  -9   9   6   0]
 [  7   5   4  -2   0  -2   7  -7   5  -3 -10   4   9  -6 -10]
 [  2 -10   6   7  -5   0  -5   0   4  -1  -8   7  -6  -6  -8]
 [  6   6   4   1  -5  -1   0  -8  -3   3  -9   5   0  -8  -4]
 [-10  -7   3   6   2   9   6   0   9  -2  -6   9   0  -2   5]
 [ -1  -8  -1  -4   6  -8   9   5   0  -2   6  -9 -10  -5  -2]
 [ -3   3   1   1   8   7  -1 -10   5   0  -9  -9   7   5  -7]
 [ -2  -8   4   3   1  -2   3   5   9   1   0   1  -8  -8  -1]
 [  6   4   1 -10  -4  -1  -4   8  -5   5   8   0  -2   7   3]
 [ -9  -9   6   3   7  -8  -2  -4  -3   0  -9   0   0  -3   5]
 [ -9  -8   1  -1   6  -5  -2   6  -6  -2   8   4  -3   0 -10]
 [ -6 -10   8   9   6   7  -9  -9   1  -5   4  -9   8   0   0]]
B^T = 
 [[  0   3  -7  -9   6 -10   7   3  -2 

5. Create two vectors c and d (1 x 20) with random inputs using np.random.

In [27]:
c = np.random.randint(10,  size=(1, 20))
d = np.random.randint(10,  size=(1, 20))

print("C =  " + str(c))
print("D =  " + str(d))

C =  [[4 4 5 6 2 0 5 3 5 8 7 7 3 1 2 9 2 6 7 8]]
D =  [[7 0 3 7 6 2 8 1 3 7 8 5 3 5 0 4 1 4 5 7]]


6. Make the product point between c and d.

In [28]:
d = d.transpose()

cd = np.dot(c,d)
print("C * D = " + str(cd))

C * D = [[469]]
