# More matrix operations

1. If possible, calculate the inverses (using the 3 methods: numpy, sympy and FERR) of matrices A, B and C. (25 pts.)

### Método 1 (numpy)

In [7]:
import numpy as np

a = np.array([[1, 2, 0], [1, 0, 1], [0, 1, 0]])
b = np.array([[2, 0, 1], [1, 1, -4], [3, 7, -3]])
c = np.array([[1, 1, 0,], [1, 0, 1], [0, 1, 0], [1, 2, 3]])

def is_square (m):
    return all (len (row) == len (m) for row in m)

def find_inverse(matrix):
    if is_square(matrix):
        if np.linalg.det(matrix) != 0:
            return np.linalg.inv(matrix)
    else:
        return "Not invertible."

print("\n A^-1 = \n" + str(find_inverse(a)))
print("\n B^-1 = \n" + str(find_inverse(b)))
print("\n C^-1 = \n" + str(find_inverse(c)))


 A^-1 = 
[[ 1.  0. -2.]
 [-0. -0.  1.]
 [-1.  1.  2.]]

 B^-1 = 
[[ 0.46296296  0.12962963 -0.01851852]
 [-0.16666667 -0.16666667  0.16666667]
 [ 0.07407407 -0.25925926  0.03703704]]

 C^-1 = 
Not invertible.


### Método 2 (simpy)

In [10]:
import sympy as sp

inversa1 = sp.Matrix(a).inv()  #sympy
print("\n A^-1 = \n" + str(inversa1))
inversa2 = sp.Matrix(b).inv()  #sympy
print("\n B^-1 = \n" + str(inversa2))
print("\n C^-1 = \n No es invertible.")



 A^-1 = 
Matrix([[1, 0, -2], [0, 0, 1], [-1, 1, 2]])

 B^-1 = 
Matrix([[25/54, 7/54, -1/54], [-1/6, -1/6, 1/6], [2/27, -7/27, 1/27]])

 C^-1 = 
 No es invertible.


### Método 3 (FERR)

In [12]:
def FERR(a):
    value = 'h' + str(sp.Matrix(a).shape)
    identity = sp.eye(int(Valor[2]))
    for x in range(0, int(Valor[2])):
        Identidad = Identidad.col_insert(x, sp.Matrix(a).col(x))
    return Identidad

print("\n A^-1 = \n" + str(Aumentar(a).rref()))
print("\n B^-1 = \n" + str(Aumentar(b).rref()))
print("\n C^-1 = \n No es invertible.")


 A^-1 = 
(Matrix([
[1, 0, 0,  1, 0, -2],
[0, 1, 0,  0, 0,  1],
[0, 0, 1, -1, 1,  2]]), (0, 1, 2))

 B^-1 = 
(Matrix([
[1, 0, 0, 25/54,  7/54, -1/54],
[0, 1, 0,  -1/6,  -1/6,   1/6],
[0, 0, 1,  2/27, -7/27,  1/27]]), (0, 1, 2))

 C^-1 = 
 No es invertible.


What differences do you observe in the output using each method? (25 pts.)

The personalized FERR method returns a duple containing the matrix and a count of its columns; the numpy returns floats and simpy returns fractions.

2. Find and interpret the range of matrices A, B and C. (25 pts.)

In [15]:
print("Rank A = " + str(np.linalg.matrix_rank(a)))
print("Rank B = " + str(np.linalg.matrix_rank(b)))
print("Rank C = " + str(np.linalg.matrix_rank(c)))
print("\nInterpretación: \nEl rango es la dimensión del espacio renglón, en este caso, las tres matrices tienen renglones de dimensión 3.")

Range A: 3
Range B: 3
Range C: 3

Interpretación: 
El rango es la dimensión del espacio renglón, en este caso, las tres matrices tienen renglones de dimensión 3.


3. Find the nulity and null space of A, B and C. (25 pts.)
Debido a que nulity(a) + rank(a) = n, en este caso, la nulidad de las tres matrices es igual a cero.

In [18]:
print("Null base A = \n" + str(sp.Matrix(a).nullspace()))
print("Null base B = \n" + str(sp.Matrix(b).nullspace()))
print("Null base  \n" + str(sp.Matrix(c).nullspace()))

Null base: 
[]
Null base: 
[]
Null base: 
[]
