# QR factorization

Investigate the use of np.linalg.qr in Python to solve the following problems. You will also use the np.transpose function that we used previously.

1. Find the QR factorization of the following matrices.

In [8]:
import numpy as np

A = np.array([[4, 0], [3, 1]])
Q, R = np.linalg.qr(A)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

Q = 
[[-0.8 -0.6]
 [-0.6  0.8]]

R = 
[[-5.  -0.6]
 [ 0.   0.8]]



In [10]:
B = np.array([[1, 2], [1, 1]])
Q, R = np.linalg.qr(B)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

Q = 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

R = 
[[-1.41421356 -2.12132034]
 [ 0.         -0.70710678]]



In [11]:
C = np.array([[2, 1], [1, -1], [2, 1]])
Q, R = np.linalg.qr(C)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

Q = 
[[-0.66666667  0.23570226]
 [-0.33333333 -0.94280904]
 [-0.66666667  0.23570226]]

R = 
[[-3.         -1.        ]
 [ 0.          1.41421356]]



In [9]:
D = np.array([[4, 8, 1], [0, 2, -2], [3, 6, 7]])
Q, R = np.linalg.qr(D)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

Q = 
[[-0.8  0.  -0.6]
 [-0.   1.   0. ]
 [-0.6  0.   0.8]]

R = 
[[ -5. -10.  -5.]
 [  0.   2.  -2.]
 [  0.   0.   5.]]



2. Use QR factorization to solve the following systems $Ax = b$, (remember that $Rx = Q^Tb$ by the properties of the orthonormal matrix).

In [12]:
A = np.array([[2, 3],[-2, -6],[1, 0]])
b = np.array([[3],[-3],[6]])
print("A = \n" + str(A) +"\n")
print("b = \n" + str(b) +"\n")

Q, R = np.linalg.qr(A)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

print("x = \n" + str(np.dot(np.transpose(Q), b)) +"\n")

A = 
[[ 2  3]
 [-2 -6]
 [ 1  0]]

b = 
[[ 3]
 [-3]
 [ 6]]

Q = 
[[-0.66666667 -0.33333333]
 [ 0.66666667 -0.66666667]
 [-0.33333333 -0.66666667]]

R = 
[[-3. -6.]
 [ 0.  3.]]

x = 
[[-6.]
 [-3.]]



In [13]:
A = np.array([[2, 4],[0, -1],[2, -1],[1,3]])
b = np.array([[-1],[3],[2],[1]])
print("A = \n" + str(A) +"\n")
print("b = \n" + str(b) +"\n")

Q, R = np.linalg.qr(A)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

print("x = \n" + str(np.dot(np.transpose(Q), b)) +"\n")

A = 
[[ 2  4]
 [ 0 -1]
 [ 2 -1]
 [ 1  3]]

b = 
[[-1]
 [ 3]
 [ 2]
 [ 1]]

Q = 
[[-0.66666667  0.47140452]
 [-0.         -0.23570226]
 [-0.66666667 -0.70710678]
 [-0.33333333  0.47140452]]

R = 
[[-3.         -3.        ]
 [ 0.          4.24264069]]

x = 
[[-1.        ]
 [-2.12132034]]



In [14]:
A = np.array([[3, -1, 2],[4, 1, 0],[-3, 2, 1],[1, 1, 5],[-2, 0, 3]])
b = np.array([[10],[10],[-5],[15],[0]])
print("A = \n" + str(A) +"\n")
print("b = \n" + str(b) +"\n")

Q, R = np.linalg.qr(A)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

print("x = \n" + str(np.dot(np.transpose(Q), b)) +"\n")

A = 
[[ 3 -1  2]
 [ 4  1  0]
 [-3  2  1]
 [ 1  1  5]
 [-2  0  3]]

b = 
[[10]
 [10]
 [-5]
 [15]
 [ 0]]

Q = 
[[-0.48038446  0.26969003 -0.4057325 ]
 [-0.64051262 -0.54936859  0.22364767]
 [ 0.48038446 -0.65924231  0.0310072 ]
 [-0.16012815 -0.42950635 -0.69139457]
 [ 0.32025631  0.07990816 -0.55351149]]

R = 
[[-6.244998    0.64051262 -0.32025631]
 [ 0.         -2.56704959 -2.02766952]
 [ 0.          0.         -5.89796509]]

x = 
[[-16.01281538]
 [ -5.94316928]
 [-12.34680276]]



In [15]:
A = np.array([[4, 2, 3, 0],[-2, 3, -1, 1],[1, 3, -4, 2],[1, 0, 1, -1],[3, 1, 3, -2]])
b = np.array([[10],[0],[2],[0],[5]])
print("A = \n" + str(A) +"\n")
print("b = \n" + str(b) +"\n")

Q, R = np.linalg.qr(A)
print("Q = \n" + str(Q) +"\n")
print("R = \n" + str(R) +"\n")

print("x = \n" + str(np.dot(np.transpose(Q), b)) +"\n")

A = 
[[ 4  2  3  0]
 [-2  3 -1  1]
 [ 1  3 -4  2]
 [ 1  0  1 -1]
 [ 3  1  3 -2]]

b = 
[[10]
 [ 0]
 [ 2]
 [ 0]
 [ 5]]

Q = 
[[-0.71842121 -0.21150374  0.2258696   0.6085938 ]
 [ 0.3592106  -0.7684636   0.52281184 -0.05163138]
 [-0.1796053  -0.59926061 -0.76877528 -0.13204504]
 [-0.1796053   0.056401    0.05246724 -0.40711782]
 [-0.53881591 -0.04935087  0.28615111 -0.66615837]]

R = 
[[-5.56776436 -1.43684242 -3.59210604  1.25723711]
 [ 0.         -4.57553099  2.43934318 -1.92468407]
 [ 0.          0.          4.14081864 -1.63950817]
 [ 0.          0.          0.          1.42371311]]

x = 
[[-10.23750222]
 [ -3.56031302]
 [  2.15190099]
 [  2.49105611]]

