# Determinants, Inverses and Cramer Rule.
You must print on console each change or operation performed.

In [3]:
import numpy as np
import sympy as sp

A = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 0]])
C = np.array([[1, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 0], [0, 1, 0, 1]])
b1 = np.array([[1], [2], [4]])
b2 = np.array([[1], [8], [4], [5]])

1. Calculate the determinants and inverses (using numpy and sympy) of A and B. (20 pts.)

In [9]:
print("\nDet(A) w/numpy = " + str(np.linalg.det(A)))
print("Det(A) w/sympy = " + str(sp.Matrix(A).det()))

print("\nDet(C) w/numpy = " + str(np.linalg.det(C)))
print("Det(C) w/sympy = " + str(sp.Matrix(C).det()))

print("\nA^-1 w/numpy = \n " + str(np.linalg.inv(A)))
print("\nA^-1 w/sympy = \n " + str(sp.Matrix(A).inv()))

print("\nC^-1 w/numpy = \n " + str(np.linalg.inv(C)))
print("\nC^-1 w/sympy = \n " + str(sp.Matrix(C).inv()))


Det(A) w/numpy = -1.0
Det(A) w/sympy = -1

Det(C) w/numpy = -1.0
Det(C) w/sympy = -1

A^-1 w/numpy = 
 [[ 1.  0. -1.]
 [-0. -0.  1.]
 [-1.  1.  1.]]

A^-1 w/sympy = 
 Matrix([[1, 0, -1], [0, 0, 1], [-1, 1, 1]])

C^-1 w/numpy = 
 [[ 1.  0.  0. -1.]
 [-0. -0.  1. -0.]
 [-1.  1.  0.  1.]
 [ 0.  0. -1.  1.]]

C^-1 w/sympy = 
 Matrix([[1, 0, 0, -1], [0, 0, 1, 0], [-1, 1, 0, 1], [0, 0, -1, 1]])


2. Solve the systems of equations with numpy, sympy and Cramer. (45 pts.)

In [15]:
import time as t

def cramer(A,b):
    sol = np.zeros((len(b),1))
    deta = round(np.linalg.det(A), 16)

    for i in range(len(b)):
        B = A.copy()
        B[:, i] = b.transpose()
        detb = round(np.linalg.det(B), 16)
        sol[i] = (detb / deta)
    return sol

#A
start=t.time()
print(cramer(A, b1))
print("cramer: "+str(t.time()-start) + "\n")

start=t.time()
print(np.dot(inva, b1))
print("numpy: "+str(t.time()-start)+ "\n")

start=t.time()
print(np.dot(inva2, b1))
print("sympy: "+str(t.time()-start)+ "\n")

[[-3.]
 [ 4.]
 [ 5.]]
cramer: 0.002012014389038086

[[-3.]
 [ 4.]
 [ 5.]]
numpy: 0.005696535110473633

[[-3]
 [4]
 [5]]
sympy: 0.0013880729675292969

[[-4.]
 [ 4.]
 [12.]
 [ 1.]]
cramer: 0.0012221336364746094

[[-4.]
 [ 4.]
 [12.]
 [ 1.]]
numpy: 0.003719806671142578

[[-4]
 [4]
 [12]
 [1]]
sympy: 0.0009093284606933594



In [16]:
#C
start = t.time()
print(cramer(C, b2))
print("cramer: "+str(t.time()-start)+ "\n")

start = t.time()
print(np.dot(avni, b2))
print("numpy: "+str(t.time()-start)+ "\n")

start = t.time()
print(np.dot(avni2, b2))
print("sympy: "+str(t.time()-start)+ "\n")

[[-4.]
 [ 4.]
 [12.]
 [ 1.]]
cramer: 0.04606151580810547

[[-4.]
 [ 4.]
 [12.]
 [ 1.]]
numpy: 0.0007948875427246094

[[-4]
 [4]
 [12]
 [1]]
sympy: 0.0011162757873535156



3. Create a C 100 𝑥 100 matrix with random inputs and a d 100 𝑥 1 vector with random inputs. Print the time it takes for each method to solve the system of equations Cx = d using all three methods. (10 pts.)

In [21]:
n = 100
c = np.random.rand(n, n)
d = np.random.rand(n, 1)

#Cramer
init = t.time()
cramer(c, d)
end = t.time()
print("cramer:" + str(end-init) + "\n")

#Numpy
init = t.time()
np.matmul(np.linalg.inv(c),d)
end = t.time()
print("numpy:" + str(end-init)+ "\n")

#Sympy
init = t.time()
irs = sp.Matrix(c).inv()
np.dot(irs, d)
end = t.time()
print("sympy:" + str(end-init)+ "\n")

cramer:0.6012065410614014

numpy:0.00319671630859375



sympy:29.265457153320312



4. Create a C 500 𝑥 500 matrix with random inputs and a d 100 𝑥 1 vector with random inputs. Print the time it takes for each method to solve the system of equations Cx = d using all three methods. (10 pts.)

In [22]:
n = 500
c = np.random.rand(n, n)
d = np.random.rand(n, 1)

#Cramer
init = t.time()
cramer(c, d)
end = t.time()
print("cramer:" + str(end-init) + "\n")

#Numpy
init = t.time()
np.matmul(np.linalg.inv(c),d)
end = t.time()
print("numpy:" + str(end-init)+ "\n")

#Sympy
init = t.time()
irs = sp.Matrix(c).inv()
np.dot(irs, d)
end = t.time()
print("sympy:" + str(end-init)+ "\n")

/usr/local/lib/python3.6/dist-packages/ipykernel/__main__.py:5: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel/__main__.py:10: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel/__main__.py:11: RuntimeWarning: invalid value encountered in double_scalars


5. Explain what differences you notice in the use of the 3 methods to solve systems of equations Cx = d. (15 pts.)

Numpy was the most efficient method, while Simpy throws an overflow. Cramer is less efficient than Numpy but does the trick as well.